--CRIA UM LOGIN DE USUARIO
CREATE LOGIN livia WITH PASSWORD = '130'

--CRIA UM USUARIO DENTRO DE UM BANCO DE DADOS
CREATE USER livia FOR LOGIN livia;

--COMANDO DENY - BLOQUEIA O ACESSO
DENY INSERT, UPDATE, DELETE
TO livia;

--COMANDO REVOKE - REVERTE A PERMISSÃO DO USUÁRIO
REVOKE INSERT, UPDATE, DELETE
TO livia;

CREATE TABLE Usuario(
	id INT NOT NULL
);

select * from Usuario

--COMANDO GRANT CONCEDE PERMISSÃO
GRANT SELECT to livia;